# Generated by Django 3.2.8 on 2021-10-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=154)),
                ('gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other'), ('4', 'Prefer Not Say')], max_length=50)),
                ('student_number', models.CharField(max_length=50)),
                ('path', models.CharField(choices=[('FSD', 'Full Stack Developer'), ('AD', 'AWS/Devops'), ('DS', 'Data Science'), ('CS', 'Cyber Security')], max_length=50)),
            ],
        ),
    ]
