# Generated by Django 3.2.8 on 2021-10-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer Not to', 'Prefer Not to')], max_length=50),
        ),
    ]
