# Generated by Django 3.2.8 on 2021-10-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregister', '0004_auto_20211020_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer Not to', 'Prefer Not to')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_register',
            name='path',
            field=models.CharField(choices=[('Full Stack Developer', 'Full Stack Developer'), ('AWS/Devops', 'AWS/Devops'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security')], max_length=50),
        ),
    ]
