# Generated by Django 3.2.8 on 2021-10-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregister', '0005_auto_20211020_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_register',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
